DROP DATABASE testphp;
CREATE DATABASE testphp;
CREATE TABLE `user` (
    USERID INT AUTO_INCREMENT NOT NULL,
    Username VARCHAR(255) NOT NULL,
    Password VARCHAR(255) NOT NULL,
    PRIMARY KEY (USERID)
);